// <auto-generated />
using System;
using ArBrain.FermentationControl.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArBrain.FermentationControl.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628191013_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArBrain.FermentationControl.Domain.Entities.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxExtract")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxPh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxTemperature")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinExtract")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinPh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinTemperature")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("ArBrain.FermentationControl.Domain.Entities.FermentationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Extract")
                        .HasColumnType("numeric");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<decimal>("Ph")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TankId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("FermentationRecords");
                });

            modelBuilder.Entity("ArBrain.FermentationControl.Domain.Entities.Tank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CapacityLiters")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tanks");
                });
#pragma warning restore 612, 618
        }
    }
}
